# PostgreSQL datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/instaclone_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Optional H2 console is no longer needed
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

# Server port
server.port=8081